swagger: "2.0"
info:
  version: 1.0.0
  title: "DISIer"
  description: "E' possibile fare delle richieste a DISIer attraverso delle API. Queste API permettono di interagire con il bot e di scoprire se una certa aula è libera in quel momento."
  termsOfService: http://swagger.io/terms/
  contact:
    name: DISIer Team
    email: davide.farina-1@studenti.unitn.it
    url: https://is2-progetto.herokuapp.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: is2-progetto.herokuapp.com
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /bot_message:
    get:
      description: |
        Risponde alla domanda fatta dall'utente. Al bot si possono chiedere informazioni riguardo agli orari degli autobus.
      operationId: botMessageGet
      parameters:
        - name: msg
          in: query
          description: Domanda da porre al bot
          required: true
          type: string
      responses:
        200:
          description: Risposta del bot
          schema:
            type: array
            items:
              $ref: '#/definitions/BotResponse'
        default:
          description: Errore
          schema:
            $ref: '#/definitions/Error'
  /pets/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: find pet by id
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: pet response
          schema:
            $ref: '#/definitions/Pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: pet deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Pet:
    allOf:
      - $ref: '#/definitions/NewPet'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewPet:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  BotResponse:
    required:
      - speech
      - displayText
      - data
      - contextOut
      - source
    properties:
      speech:
        type: string
      displayText:
        type: string
      data: 
        type: object
      contextOut:
        type: array
      source:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string